-- MySQL Script generated by MySQL Workbench
-- Wed Apr 24 13:36:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema culdampolla
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `culdampolla` ;

-- -----------------------------------------------------
-- Schema culdampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `culdampolla` DEFAULT CHARACTER SET utf8 ;
USE `culdampolla` ;

-- -----------------------------------------------------
-- Table `culdampolla`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombreProveedor` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(75) NOT NULL,
  `telFijo` VARCHAR(14) NOT NULL,
  `telMob` VARCHAR(14) NULL,
  `fax` VARCHAR(14) NULL,
  `nif` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`gafa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`gafa` (
  `idGafa` INT NOT NULL AUTO_INCREMENT,
  `idProveedor` INT NOT NULL,
  `marca` VARCHAR(50) NOT NULL,
  `grabacionDerecha` FLOAT NOT NULL,
  `grabacionIzquierda` FLOAT NOT NULL,
  `colorMontura` VARCHAR(45) NOT NULL,
  `colorCristal` VARCHAR(30) NOT NULL,
  `tipoMontura` VARCHAR(12) NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`idGafa`),
  INDEX `idProveedor_idx` (`idProveedor` ASC) VISIBLE,
  CONSTRAINT `idProveedor`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `culdampolla`.`proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `recomendado` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `recomendado_idx` (`recomendado` ASC) VISIBLE,
  CONSTRAINT `recomendado`
    FOREIGN KEY (`recomendado`)
    REFERENCES `culdampolla`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culdampolla`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culdampolla`.`venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `idGafa` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `fechaVenta` DATE NOT NULL,
  `empleado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `idGafa_idx` (`idGafa` ASC) VISIBLE,
  INDEX `idCliente_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `idGafa`
    FOREIGN KEY (`idGafa`)
    REFERENCES `culdampolla`.`gafa` (`idGafa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `culdampolla`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
