-- MySQL Script generated by MySQL Workbench
-- Tue Apr 30 00:49:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pizzeria` ;

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8mb3 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`provincia` (
  `Id_Provincia` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Provincia` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Id_Provincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`localidad` (
  `Id_Localidad` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Localidad` VARCHAR(50) NOT NULL,
  `Id_Provincia` INT NOT NULL,
  PRIMARY KEY (`Id_Localidad`),
  INDEX `Id_Provincia_idx` (`Id_Provincia` ASC) VISIBLE,
  CONSTRAINT `Id_Provincia`
    FOREIGN KEY (`Id_Provincia`)
    REFERENCES `pizzeria`.`provincia` (`Id_Provincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`cliente` (
  `Nr_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(35) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `Direccion` VARCHAR(65) NOT NULL,
  `Codigo_Postal` INT NOT NULL,
  `NumeroTel` VARCHAR(14) NOT NULL,
  `Id_Localidad` INT NOT NULL,
  PRIMARY KEY (`Nr_Cliente`),
  INDEX `Id_Localidad_idx` (`Id_Localidad` ASC) VISIBLE,
  CONSTRAINT `FK_Cliente_Localidad`
    FOREIGN KEY (`Id_Localidad`)
    REFERENCES `pizzeria`.`localidad` (`Id_Localidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`tienda` (
  `Id_Tienda` INT NOT NULL AUTO_INCREMENT,
  `Direccion` VARCHAR(65) NOT NULL,
  `Codigo_Postal` INT NOT NULL,
  `Id_Localidad` INT NOT NULL,
  PRIMARY KEY (`Id_Tienda`),
  INDEX `Id_Localidad_idx` (`Id_Localidad` ASC) VISIBLE,
  CONSTRAINT `FK_Tienda_Localidad`
    FOREIGN KEY (`Id_Localidad`)
    REFERENCES `pizzeria`.`localidad` (`Id_Localidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleado` (
  `Id_Empleado` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(35) NOT NULL,
  `Apellidos` VARCHAR(55) NOT NULL,
  `NIF` VARCHAR(15) NOT NULL,
  `Telefono` VARCHAR(14) NOT NULL,
  `Puesto` VARCHAR(40) NOT NULL,
  `Id_Tienda` INT NOT NULL,
  PRIMARY KEY (`Id_Empleado`),
  INDEX `Id_Tienda_idx` (`Id_Tienda` ASC) VISIBLE,
  CONSTRAINT `Id_Tienda`
    FOREIGN KEY (`Id_Tienda`)
    REFERENCES `pizzeria`.`tienda` (`Id_Tienda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pedido` (
  `Id_Pedido` INT NOT NULL AUTO_INCREMENT,
  `FechaHoraPedido` DATETIME NOT NULL,
  `Direccion_Reparto/Recojida` VARCHAR(70) NOT NULL,
  `FechaHoraEntrega` DATETIME NOT NULL,
  `Precio_Total` FLOAT NOT NULL,
  `Nr_Cliente` INT NOT NULL,
  `Id_Tienda` INT NOT NULL,
  `Id_Empleado` INT NOT NULL,
  PRIMARY KEY (`Id_Pedido`),
  INDEX `Id_Cliente_idx` (`Nr_Cliente` ASC) VISIBLE,
  INDEX `Id_Tienda_idx` (`Id_Tienda` ASC) VISIBLE,
  INDEX `Id_Empleado_idx` (`Id_Empleado` ASC) VISIBLE,
  CONSTRAINT `FK_Pedido_Cliente`
    FOREIGN KEY (`Nr_Cliente`)
    REFERENCES `pizzeria`.`cliente` (`Nr_Cliente`),
  CONSTRAINT `FK_Pedido_Empleado`
    FOREIGN KEY (`Id_Empleado`)
    REFERENCES `pizzeria`.`empleado` (`Id_Empleado`),
  CONSTRAINT `FK_Pedido_Tienda`
    FOREIGN KEY (`Id_Tienda`)
    REFERENCES `pizzeria`.`tienda` (`Id_Tienda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`categoriaproducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categoriaproducto` (
  `Id_CategoriaProducto` INT NOT NULL AUTO_INCREMENT,
  `Categoria` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id_CategoriaProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`productopedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`productopedido` (
  `Id_ProductoPedido` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Informacion_Producto` VARCHAR(70) NOT NULL,
  `Imagen` LONGBLOB NULL DEFAULT NULL,
  `Precio` FLOAT NOT NULL,
  `Id_CategoriaProducto` INT NOT NULL,
  PRIMARY KEY (`Id_ProductoPedido`),
  INDEX `Id_CategoriaProducto_idx` (`Id_CategoriaProducto` ASC) VISIBLE,
  CONSTRAINT `Id_CategoriaProducto`
    FOREIGN KEY (`Id_CategoriaProducto`)
    REFERENCES `pizzeria`.`categoriaproducto` (`Id_CategoriaProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`cantidadtotalproducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`cantidadtotalproducto` (
  `Id_CantidadTotalProducto` INT NOT NULL AUTO_INCREMENT,
  `Id_Pedido` INT NOT NULL,
  `Id_ProductoPedido` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`Id_CantidadTotalProducto`),
  INDEX `Id_Pedido_idx` (`Id_Pedido` ASC) VISIBLE,
  INDEX `Id_ProductoPedido_idx` (`Id_ProductoPedido` ASC) VISIBLE,
  CONSTRAINT `Id_Pedido`
    FOREIGN KEY (`Id_Pedido`)
    REFERENCES `pizzeria`.`pedido` (`Id_Pedido`),
  CONSTRAINT `Id_ProductoPedido`
    FOREIGN KEY (`Id_ProductoPedido`)
    REFERENCES `pizzeria`.`productopedido` (`Id_ProductoPedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
