-- MySQL Script generated by MySQL Workbench
-- Tue Apr 30 03:01:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `youtube` ;

-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `youtube` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `youtube` ;

-- -----------------------------------------------------
-- Table `youtube`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`usuarios` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(255) NULL DEFAULT NULL,
  `Contraseña` VARCHAR(255) NULL DEFAULT NULL,
  `Nombre_usuario` VARCHAR(255) NULL DEFAULT NULL,
  `Fecha_nacimiento` DATE NULL DEFAULT NULL,
  `Sexo` VARCHAR(10) NULL DEFAULT NULL,
  `País` VARCHAR(255) NULL DEFAULT NULL,
  `Código_postal` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`canales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`canales` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NULL DEFAULT NULL,
  `Descripción` TEXT NULL DEFAULT NULL,
  `Fecha_creación` DATE NULL DEFAULT NULL,
  `Usuario_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Usuario_ID` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `canales_ibfk_1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `youtube`.`usuarios` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`videos` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Título` VARCHAR(255) NULL DEFAULT NULL,
  `Descripción` TEXT NULL DEFAULT NULL,
  `Tamaño` INT NULL DEFAULT NULL,
  `Nombre_archivo` VARCHAR(255) NULL DEFAULT NULL,
  `Duración` TIME NULL DEFAULT NULL,
  `Thumbnail` VARCHAR(255) NULL DEFAULT NULL,
  `Número_reproducciones` INT NULL DEFAULT NULL,
  `Número_likes` INT NULL DEFAULT NULL,
  `Número_dislikes` INT NULL DEFAULT NULL,
  `Estado` ENUM('público', 'oculto', 'privado') NULL DEFAULT NULL,
  `Usuario_ID` INT NULL DEFAULT NULL,
  `Fecha_publicación` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Usuario_ID` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `videos_ibfk_1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `youtube`.`usuarios` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`comentarios` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Texto_comentario` TEXT NULL DEFAULT NULL,
  `Fecha_creación` DATETIME NULL DEFAULT NULL,
  `Usuario_ID` INT NULL DEFAULT NULL,
  `Video_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Usuario_ID` (`Usuario_ID` ASC) VISIBLE,
  INDEX `Video_ID` (`Video_ID` ASC) VISIBLE,
  CONSTRAINT `comentarios_ibfk_1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `youtube`.`usuarios` (`ID`),
  CONSTRAINT `comentarios_ibfk_2`
    FOREIGN KEY (`Video_ID`)
    REFERENCES `youtube`.`videos` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`dislikes_comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`dislikes_comentarios` (
  `Usuario_ID` INT NOT NULL,
  `Comentario_ID` INT NOT NULL,
  PRIMARY KEY (`Usuario_ID`, `Comentario_ID`),
  INDEX `Comentario_ID` (`Comentario_ID` ASC) VISIBLE,
  CONSTRAINT `dislikes_comentarios_ibfk_1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `youtube`.`usuarios` (`ID`),
  CONSTRAINT `dislikes_comentarios_ibfk_2`
    FOREIGN KEY (`Comentario_ID`)
    REFERENCES `youtube`.`comentarios` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`dislikes_videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`dislikes_videos` (
  `Usuario_ID` INT NOT NULL,
  `Video_ID` INT NOT NULL,
  PRIMARY KEY (`Usuario_ID`, `Video_ID`),
  INDEX `Video_ID` (`Video_ID` ASC) VISIBLE,
  CONSTRAINT `dislikes_videos_ibfk_1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `youtube`.`usuarios` (`ID`),
  CONSTRAINT `dislikes_videos_ibfk_2`
    FOREIGN KEY (`Video_ID`)
    REFERENCES `youtube`.`videos` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`etiquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`etiquetas` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre_etiqueta` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`likes_comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`likes_comentarios` (
  `Usuario_ID` INT NOT NULL,
  `Comentario_ID` INT NOT NULL,
  PRIMARY KEY (`Usuario_ID`, `Comentario_ID`),
  INDEX `Comentario_ID` (`Comentario_ID` ASC) VISIBLE,
  CONSTRAINT `likes_comentarios_ibfk_1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `youtube`.`usuarios` (`ID`),
  CONSTRAINT `likes_comentarios_ibfk_2`
    FOREIGN KEY (`Comentario_ID`)
    REFERENCES `youtube`.`comentarios` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`likes_videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`likes_videos` (
  `Usuario_ID` INT NOT NULL,
  `Video_ID` INT NOT NULL,
  PRIMARY KEY (`Usuario_ID`, `Video_ID`),
  INDEX `Video_ID` (`Video_ID` ASC) VISIBLE,
  CONSTRAINT `likes_videos_ibfk_1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `youtube`.`usuarios` (`ID`),
  CONSTRAINT `likes_videos_ibfk_2`
    FOREIGN KEY (`Video_ID`)
    REFERENCES `youtube`.`videos` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`playlists` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NULL DEFAULT NULL,
  `Fecha_creación` DATE NULL DEFAULT NULL,
  `Estado` ENUM('pública', 'privada') NULL DEFAULT NULL,
  `Usuario_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Usuario_ID` (`Usuario_ID` ASC) VISIBLE,
  CONSTRAINT `playlists_ibfk_1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `youtube`.`usuarios` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`suscripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`suscripciones` (
  `Usuario_ID` INT NOT NULL,
  `Canal_ID` INT NOT NULL,
  PRIMARY KEY (`Usuario_ID`, `Canal_ID`),
  INDEX `Canal_ID` (`Canal_ID` ASC) VISIBLE,
  CONSTRAINT `suscripciones_ibfk_1`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `youtube`.`usuarios` (`ID`),
  CONSTRAINT `suscripciones_ibfk_2`
    FOREIGN KEY (`Canal_ID`)
    REFERENCES `youtube`.`canales` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`video_etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`video_etiqueta` (
  `Video_ID` INT NOT NULL,
  `Etiqueta_ID` INT NOT NULL,
  PRIMARY KEY (`Video_ID`, `Etiqueta_ID`),
  INDEX `Etiqueta_ID` (`Etiqueta_ID` ASC) VISIBLE,
  CONSTRAINT `video_etiqueta_ibfk_1`
    FOREIGN KEY (`Video_ID`)
    REFERENCES `youtube`.`videos` (`ID`),
  CONSTRAINT `video_etiqueta_ibfk_2`
    FOREIGN KEY (`Etiqueta_ID`)
    REFERENCES `youtube`.`etiquetas` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`videos_playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`videos_playlists` (
  `Video_ID` INT NOT NULL,
  `Playlist_ID` INT NOT NULL,
  PRIMARY KEY (`Video_ID`, `Playlist_ID`),
  INDEX `Playlist_ID` (`Playlist_ID` ASC) VISIBLE,
  CONSTRAINT `videos_playlists_ibfk_1`
    FOREIGN KEY (`Video_ID`)
    REFERENCES `youtube`.`videos` (`ID`),
  CONSTRAINT `videos_playlists_ibfk_2`
    FOREIGN KEY (`Playlist_ID`)
    REFERENCES `youtube`.`playlists` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
